name: PHPUnit tests

on:
  push:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: paymon
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Start MySQL
        run: |
          sudo service mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, exif, imagick, bcmath, redis
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install composer dependencies
        run: composer install --ignore-platform-reqs

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Run tests
        run: ./vendor/bin/phpunit -d memory_limit=2048M